export default {
  PREVIOUS_CONNECTION: 0,
  INPUT_CONNECITON: 1,
  NEXT_CONNECTION: 2,
  OUTPUT_CONNECTION: 3,
  DEFAULT_POSITION: { x: 15, y: 25 },
  PREVIOUS_NEXT_POS_X: 24,
  CHILD_NEXT_POS_X: 48,
  BLOCK_HEAD_HEIGHT: 36,
  BLOCK_TAIL_HEIGHT: 30,
  PIXEL: 6,
};
