export default {
  bgColor: '#FAFAFA',
  headerColor: '#2176C5',
  projectBgColor: '#F2FAFF',
  mainBorderColor: '#d8d8d8',
  motionColor: '#5c98fe',
  motionStrokeColor: '#4289eb',
  eventsColor: '#f2d402',
  eventsStrokeColor: '#e2b11c',
  controlColor: '#ecaa1b',
  controlStrokeColor: '#ec9e18',
  sensingColor: '#67bfe6',
  sensingStrokeColor: '#5cb1d6',
  operatorsColor: '#58bf4a',
  operatorsStrokeColor: '#4eb14e',
  variablesColor: '#e9891d',
  variablesStrokeColor: '#db6e00',
  myblocksColor: '#e76280',
  myblocksStrokeColor: '#ff3355',
  typeHoverColor: '#4280d7',
  lightGreyColor: '#fafafa',
};