export default {
  bgColor: '#FAFAFA',
  headerColor: '#2176C5',
  projectBgColor: '#F2FAFF',
  mainBorderColor: '#d8d8d8',
  motionColor: '#5c98fe',
  eventsColor: '#f2d402',
  controlColor: '#ecaa1b',
  sensingColor: '#67bfe6',
  operatorsColor: '#58bf4a',
  variablesColor: '#e9891d',
  myblocksColor: '#e76280',
  typeHoverColor: '#4280d7',
  lightGreyColor: '#fafafa',
};
